# Generated by Django 3.2.18 on 2023-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230406_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
