# Generated by Django 3.2.18 on 2023-04-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notice',
            field=models.BooleanField(default=False),
        ),
    ]
