# Generated by Django 3.2.18 on 2023-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(default='기타', max_length=20),
            preserve_default=False,
        ),
    ]
