# Generated by Django 3.2.18 on 2023-04-14 05:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=accounts.models.User.profile_img_path),
        ),
    ]
